FROM tomcat:9
#WORKDIR /tmp
COPY ./ssc.war /usr/local/tomcat/webapps
#RUN cp fortify.license /root/.fortify/ssc/conf/temp-fortify.license
#RUN sed -i 's/host\.url=.*/host\.url=http\:\/\/test\.fortify\.com/g' /root/.fortify/ssc/conf/temp-app.properties
#RUN cat /root/.fortify/ssc/init.token